gl_log_file = "gl.log"

skybox_panel = "skybox_panel.png"
ground_plane_tex = "tile_rock_planet256x256.png"
text_font_sheet = "text_font2048x2048.png"
title_font_sheet = "title_font2048x2048.png"

# Asset paths
shader_path = "shaders"
asset_path = "assets"


[[platform]]
# Platform specific parameters

[macos]
shader_version = "330"

[windows]
shader_version = "330"

[linux]
# Linux
shader_version = "420"
