# Open GL log file name.
gl_log_file = "gl.log"

# Asset paths
asset_path = "assets"

# Shader paths.
shader_path = "shaders"
shader_version = "420"

[platform]
# Platform specific parameters.

[platform.macos]
shader_version = "330"

[platform.windows]
shader_version = "330"

[platform.linux]
shader_version = "420"
